name: example

on:
  push:
    branches:
      - main

jobs:
    example:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pages: write
          id-token: write
        concurrency:
          group: "pages"
          cancel-in-progress: false
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set Node.js 20.11.0
            uses: actions/setup-node@v3
            with:
              node-version: 20.11.0
          - name: Install Dependencies
            run: npm ci
          - name: Install Dependencies for example
            run: npm ci
            working-directory: ./examples/restaurants
          - name: Setup Pages
            uses: actions/configure-pages@v4
          - name: Build example
            run: npm run build 
            working-directory: ./examples/restaurants
          - name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
              path: './examples/restaurants/dist'
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4